# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'TestTask' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire', '~> 5.4'

  # Pods for TestTask

end
